// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using employee_payroll.Data;

#nullable disable

namespace employee_payroll.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250813140707_newMigration")]
    partial class newMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("employee_payroll.Models.Entities.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("is_active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("employee_payroll.Models.Entities.Payroll", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("amount_paid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("date_paid")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("employee_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("employee_id");

                    b.ToTable("payrolls");
                });

            modelBuilder.Entity("employee_payroll.Models.Entities.Payroll", b =>
                {
                    b.HasOne("employee_payroll.Models.Entities.Employee", "employee")
                        .WithMany("payroll_history")
                        .HasForeignKey("employee_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");
                });

            modelBuilder.Entity("employee_payroll.Models.Entities.Employee", b =>
                {
                    b.Navigation("payroll_history");
                });
#pragma warning restore 612, 618
        }
    }
}
